In [4]:
import pandas as pd
car=pd.Series(["Benz","TATA","Honda","BMW"])
car

0     Benz
1     TATA
2    Honda
3      BMW
dtype: str

In [6]:
car.loc[3:10]

3    BMW
dtype: str

In [7]:
print(car.dtype)

str

In [8]:
print(car.shape)

(4,)

In [9]:
print(car.size)

4

In [10]:
print(car[1])

TATA

In [11]:
car.isna().sum()

np.int64(0)

In [12]:
car.info()

<class 'pandas.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: None
Non-Null Count  Dtype
--------------  -----
4 non-null      str
dtypes: str(1)
memory usage: 164.0 bytes

In [13]:
color=pd.Series(["Red","Blue","Black","White"])
color

0      Red
1     Blue
2    Black
3    White
dtype: str

In [16]:
data=pd.DataFrame({
    "Name":car,
    "color":color
})
data

    Name  color
0   Benz    Red
1   TATA   Blue
2  Honda  Black
3    BMW  White

In [18]:
print(data.dtypes)
print()
print(data.shape)
print()
print(data.size)

Name     str
color    str
dtype: object

(4, 2)

8

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   color   4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [20]:
data.isna().sum()

Name     0
color    0
dtype: int64

In [21]:
data.notna().sum()

Name     4
color    4
dtype: int64

In [22]:
import pandas as pd

student_data = {
    'Name': ['Ram', 'Divya', 'Kabilan', 'Nisha'],
    'class':[8,7,9,6]
}


df = pd.DataFrame(student_data)
df

      Name  class
0      Ram      8
1    Divya      7
2  Kabilan      9
3    Nisha      6

In [23]:
df=pd.read_csv("C:\\Users\\mahima\\Downloads\\employees.csv")
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [24]:
df.to_csv("user.csv",index=False)

In [25]:
new_df=pd.read_csv("user.csv")
new_df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [26]:
print(new_df.dtypes)

EMPLOYEE_ID       int64
FIRST_NAME          str
LAST_NAME           str
EMAIL               str
PHONE_NUMBER        str
HIRE_DATE           str
JOB_ID              str
SALARY            int64
COMMISSION_PCT      str
MANAGER_ID          str
DEPARTMENT_ID     int64
dtype: object

In [27]:
new_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     50 non-null     int64
 1   FIRST_NAME      50 non-null     str
 2   LAST_NAME       50 non-null     str
 3   EMAIL           50 non-null     str
 4   PHONE_NUMBER    50 non-null     str
 5   HIRE_DATE       50 non-null     str
 6   JOB_ID          50 non-null     str
 7   SALARY          50 non-null     int64
 8   COMMISSION_PCT  50 non-null     str
 9   MANAGER_ID      50 non-null     str
 10  DEPARTMENT_ID   50 non-null     int64
dtypes: int64(3), str(8)
memory usage: 4.4 KB

In [28]:
new_df.isna().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

In [29]:
new_df.describe()

       EMPLOYEE_ID        SALARY  DEPARTMENT_ID
count    50.000000     50.000000       50.00000
mean    134.760000   6182.320000       57.60000
std      33.631594   4586.181772       25.11687
min     100.000000   2100.000000       10.00000
25%     112.250000   2725.000000       50.00000
50%     124.500000   4600.000000       50.00000
75%     136.750000   8150.000000       60.00000
max     206.000000  24000.000000      110.00000

In [30]:
new_df.head(5)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [31]:
new_df.tail(5)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [32]:
new_df.loc[0]

EMPLOYEE_ID                198
FIRST_NAME              Donald
LAST_NAME             OConnell
EMAIL                 DOCONNEL
PHONE_NUMBER      650.507.9833
HIRE_DATE            21-JUN-07
JOB_ID                SH_CLERK
SALARY                    2600
COMMISSION_PCT              -
MANAGER_ID                 124
DEPARTMENT_ID               50
Name: 0, dtype: object

In [38]:
c=pd.Series(["Red","Blue","White","Black"],index=[1,2,3,4])
c

1      Red
2     Blue
3    White
4    Black
dtype: str

In [39]:
c.loc[2:4]

2     Blue
3    White
4    Black
dtype: str

In [40]:
c.iloc[1:10]

2     Blue
3    White
4    Black
dtype: str

In [41]:
new_df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [47]:
new_df.EMAIL

0     DOCONNEL
1       DGRANT
2      JWHALEN
3     MHARTSTE
4         PFAY
5      SMAVRIS
6        HBAER
7     SHIGGINS
8       WGIETZ
9        SKING
10    NKOCHHAR
11     LDEHAAN
12     AHUNOLD
13      BERNST
14     DAUSTIN
15    VPATABAL
16    DLORENTZ
17    NGREENBE
18     DFAVIET
19       JCHEN
20    ISCIARRA
21     JMURMAN
22       LPOPP
23    DRAPHEAL
24       AKHOO
25      SBAIDA
26     STOBIAS
27     GHIMURO
28    KCOLMENA
29      MWEISS
30      AFRIPP
31    PKAUFLIN
32    SVOLLMAN
33    KMOURGOS
34      JNAYER
35    IMIKKILI
36     JLANDRY
37     SMARKLE
38     LBISSOT
39    MATKINSO
40     JAMRLOW
41     TJOLSON
42     JMALLIN
43     MROGERS
44        KGEE
45    HPHILTAN
46     RLADWIG
47     SSTILES
48        JSEO
49      JPATEL
Name: EMAIL, dtype: str

In [48]:
new_df["SALARY"]

0      2600
1      2600
2      4400
3     13000
4      6000
5      6500
6     10000
7     12008
8      8300
9     24000
10    17000
11    17000
12     9000
13     6000
14     4800
15     4800
16     4200
17    12008
18     9000
19     8200
20     7700
21     7800
22     6900
23    11000
24     3100
25     2900
26     2800
27     2600
28     2500
29     8000
30     8200
31     7900
32     6500
33     5800
34     3200
35     2700
36     2400
37     2200
38     3300
39     2800
40     2500
41     2100
42     3300
43     2900
44     2400
45     2200
46     3600
47     3200
48     2700
49     2500
Name: SALARY, dtype: int64

In [49]:
new_df["EMAIL"].value_counts()

EMAIL
DOCONNEL    1
DGRANT      1
JWHALEN     1
MHARTSTE    1
PFAY        1
SMAVRIS     1
HBAER       1
SHIGGINS    1
WGIETZ      1
SKING       1
NKOCHHAR    1
LDEHAAN     1
AHUNOLD     1
BERNST      1
DAUSTIN     1
VPATABAL    1
DLORENTZ    1
NGREENBE    1
DFAVIET     1
JCHEN       1
ISCIARRA    1
JMURMAN     1
LPOPP       1
DRAPHEAL    1
AKHOO       1
SBAIDA      1
STOBIAS     1
GHIMURO     1
KCOLMENA    1
MWEISS      1
AFRIPP      1
PKAUFLIN    1
SVOLLMAN    1
KMOURGOS    1
JNAYER      1
IMIKKILI    1
JLANDRY     1
SMARKLE     1
LBISSOT     1
MATKINSO    1
JAMRLOW     1
TJOLSON     1
JMALLIN     1
MROGERS     1
KGEE        1
HPHILTAN    1
RLADWIG     1
SSTILES     1
JSEO        1
JPATEL      1
Name: count, dtype: int64

In [50]:
new_df[new_df["EMAIL"]=="JPATEL"]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [54]:
pd.crosstab(new_df["EMAIL"],new_df["SALARY"])

SALARY,2100,2200,2400,2500,2600,2700,2800,2900,3100,3200,...,8000,8200,8300,9000,10000,11000,12008,13000,17000,24000
EMAIL,,,,,,,,,,,,,,,,,,,,,
AFRIPP,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
AHUNOLD,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
AKHOO,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
BERNST,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DAUSTIN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DFAVIET,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
DGRANT,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DLORENTZ,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DOCONNEL,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DRAPHEAL,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
GHIMURO,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
HBAER,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
HPHILTAN,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
IMIKKILI,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ISCIARRA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
JAMRLOW,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
JCHEN,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
JLANDRY,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
JMALLIN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
JMURMAN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
JNAYER,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
JPATEL,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
JSEO,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
JWHALEN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
KCOLMENA,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
KGEE,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
KMOURGOS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LBISSOT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LDEHAAN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
LPOPP,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MATKINSO,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MHARTSTE,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
MROGERS,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
MWEISS,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
NGREENBE,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
NKOCHHAR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
PFAY,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PKAUFLIN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
RLADWIG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SBAIDA,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
SHIGGINS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
SKING,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
SMARKLE,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SMAVRIS,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SSTILES,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
STOBIAS,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SVOLLMAN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TJOLSON,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VPATABAL,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
WGIETZ,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0